"""Add student to Meeting

Revision ID: 25b1a42eea8a
Revises: 37235a9bc2b6
Create Date: 2025-08-10 20:35:43.274598

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '25b1a42eea8a'
down_revision = '37235a9bc2b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_record', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'student', ['student_id'], ['id'])

    with op.batch_alter_table('corporate_training', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'course', ['course_id'], ['id'])

    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['created_by_id'], ['id'])
        batch_op.create_foreign_key(None, 'course', ['course_interest_id'], ['id'])

    with op.batch_alter_table('lead_interaction', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['created_by_id'], ['id'])
        batch_op.create_foreign_key(None, 'lead', ['lead_id'], ['id'])

    with op.batch_alter_table('meeting', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['created_by_id'], ['id'])
        batch_op.create_foreign_key(None, 'lead', ['lead_id'], ['id'])
        batch_op.create_foreign_key(None, 'student', ['student_id'], ['id'])

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('country_code', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('schedule_days', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('schedule_time', sa.String(length=20), nullable=True))
        batch_op.create_foreign_key(None, 'course', ['course_id'], ['id'])
        batch_op.create_foreign_key(None, 'lead', ['lead_id'], ['id'])
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('schedule_time')
        batch_op.drop_column('schedule_days')
        batch_op.drop_column('country_code')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    with op.batch_alter_table('meeting', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('lead_interaction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('corporate_training', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('attendance_record', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
