"""Add settings to Meeting

Revision ID: 37235a9bc2b6
Revises: 0b584ffd757c
Create Date: 2025-08-10 20:17:22.759982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37235a9bc2b6'
down_revision = '0b584ffd757c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_record', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'student', ['student_id'], ['id'])

    with op.batch_alter_table('corporate_training', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'course', ['course_id'], ['id'])

    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['created_by_id'], ['id'])
        batch_op.create_foreign_key(None, 'course', ['course_interest_id'], ['id'])

    with op.batch_alter_table('lead_interaction', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'lead', ['lead_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['created_by_id'], ['id'])

    with op.batch_alter_table('meeting', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'lead', ['lead_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['created_by_id'], ['id'])
        batch_op.create_foreign_key(None, 'student', ['student_id'], ['id'])

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'lead', ['lead_id'], ['id'])
        batch_op.create_foreign_key(None, 'course', ['course_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('meeting', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('lead_interaction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('corporate_training', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('attendance_record', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
