"""Add corporate_leads to Meeting

Revision ID: 70ce55c14d9f
Revises: 25b1a42eea8a
Create Date: 2025-08-10 21:27:28.395457

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '70ce55c14d9f'
down_revision = '25b1a42eea8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_record', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'student', ['student_id'], ['id'])

    with op.batch_alter_table('corporate_training', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('contact_person_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('contact_person_email', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('contact_person_country_code', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('contact_person_phone', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('course_names', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('quotation_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('expected_start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['created_by_id'], ['id'])
        batch_op.drop_column('course_id')
        batch_op.drop_column('contact_email')
        batch_op.drop_column('contact_person')
        batch_op.drop_column('contact_phone')

    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'course', ['course_interest_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['created_by_id'], ['id'])

    with op.batch_alter_table('lead_interaction', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['created_by_id'], ['id'])
        batch_op.create_foreign_key(None, 'lead', ['lead_id'], ['id'])

    with op.batch_alter_table('meeting', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'lead', ['lead_id'], ['id'])
        batch_op.create_foreign_key(None, 'student', ['student_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['created_by_id'], ['id'])

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'course', ['course_id'], ['id'])
        batch_op.create_foreign_key(None, 'lead', ['lead_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('meeting', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('lead_interaction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('corporate_training', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_phone', mysql.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('contact_person', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('contact_email', mysql.VARCHAR(length=120), nullable=False))
        batch_op.add_column(sa.Column('course_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('created_by_id')
        batch_op.drop_column('expected_start_date')
        batch_op.drop_column('quotation_amount')
        batch_op.drop_column('course_names')
        batch_op.drop_column('contact_person_phone')
        batch_op.drop_column('contact_person_country_code')
        batch_op.drop_column('contact_person_email')
        batch_op.drop_column('contact_person_name')
        batch_op.drop_column('location')

    with op.batch_alter_table('attendance_record', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
